### ISSUE TITLE
Not running correctly?

### ISSUE THREAD

**Issue by Bluebird45** [zakkor/rocket#1]
Is this a work in progress or am I doing something wrong? On Debian 8.3 64-bit, Rust 1.8, and OpenGL 2.1.

The program compiles and runs, but for ten seconds or so all it has is a scrolling starfield with three horizontal colored bars (red, blue or green) moving up the window. Any mouse or keyboard input during this stage will cause the program to exit.

After the colored bars have gone, then it is perfectly stable. There is a colored square that moves horizontally, but not vertically, in response to mouse movements. The square also changes color (red, blue or green) with mouse clicks. The terminal window shows the keys being pressed, although they have no effect on the program.

**Comment by zakkor** [comment]
Hey there, this is definitely a work in progress, I didn't really expect anyone else to even see the repo.

That being said, you can only pass through the bars if you are the same color as them (changed by clicking, as you noticed), colliding with a bar while not being the same color as it will end the game -- currently closes the program because of laziness.

The reason for horizontal movement is because some bars are a color you can't switch to (like the last bar that comes), so you have to pass through the gap.

If you wish to fiddle with it yourself, this is the code that handles the creation and position of the bars:

`squares: vec![ ColoredRect::new().width_height(640.0, 50.0).color(GREY).position(0.0, -200.0), ...]`

Not really sure why any keyboard or mouse input would close the game, though.
